### ISSUE TITLE
MELPA?

### ISSUE THREAD

**Issue by jtzeng** [don9z/blackboard-theme#2]
Hey, it'd be really cool if you can add this to MELPA.

Thanks!

**Comment by GallagherCommaJack** [comment]
bump

**Comment by andreis** [comment]
+1

**Comment by jtzeng** [comment]
What are the rules on adding somebody else's repo to MELPA ourselves?

**Comment by don9z** [comment]
Pull request submitted

https://github.com/melpa/melpa/pull/4459
