### ISSUE TITLE
Please add MELPA-compatible Git tags

### ISSUE THREAD

**Issue by mzuther** [don9z/blackboard-theme#5]
Hi!

I have just switched my Emacs package repository from MELPA [unstable](https://melpa.org/) to [stable](https://stable.melpa.org/). The stable repository only contains packages that have a version number, instead of compiling from the latest commit.  This is a measure to protect users from using "patchy" code.

As this is a great idea, I'd like to ask you to add compatible tags to your Git repository.  Tagging is as simple as

    $ git tag v1.0 d8b984f

I personally use version numbers like `v1.2.3`, but `1.2.3` or `1.2` work just as well.  And don't fear, you only have to tag the latest stable version...

Unfortunately, Git doesn't push tags automatically.  So after you are done (or in case you've already tagged some of your commits and the tags don't show up), you have to manually push the tags to the Git repository:

    $ git push --tags origin

Now, everytime you reach a stable state, add a new tag to that commit. The actual transition to the stable repository should happen automatically.

In addition to the above, it's probably a good idea to place the version number at a prominent place in your main script.  This and tagging your stable commits will make it easier for your users to find and compare different releases.  So you see, there's a lot to win and nothing to lose... :)

Thanks for listening!

Martin

**Comment by don9z** [comment]
Done.

**Comment by mzuther** [comment]
Thanks! :)
